#!/bin/bash

# Podman installation script for Debian
# Executes commands in the specified order

set -o pipefail

echo "=========================================="
echo "Starting Podman installation on Debian"
echo "=========================================="

# 1. Update and upgrade system
echo "Step 1: Updating and upgrading system..."
sudo apt update && sudo apt upgrade -y

# 2. Install Podman
echo "Step 2: Installing Podman..."
sudo apt install -y podman

# 3. Install supporting packages
echo "Step 3: Installing supporting packages..."
sudo apt install -y uidmap slirp4netns dbus-user-session fuse-overlayfs

# 4. Enable linger for user
echo "Step 4: Enabling linger for user $USER..."
sudo loginctl enable-linger $USER

# 5. Check linger status
echo "Step 5: Checking linger status..."
loginctl show-user $USER | grep Linger

# 6. Install podman-compose
echo "Step 6: Installing podman-compose..."
sudo apt install -y podman-compose

# 7. Check podman-compose version
echo "Step 7: Checking podman-compose version..."
podman-compose --version

# 8. Test with hello-world
echo "Step 8: Running hello-world test..."
podman run hello-world

# 9. Edit registry configuration
echo "Step 9: Editing registry configuration..."
echo "Opening /etc/containers/registries.conf with nano"
echo "Add the following line:"
echo "unqualified-search-registries = [\"docker.io\", \"ghcr.io\", \"dock.mau.dev\"]"
echo ""
sudo nano /etc/containers/registries.conf

# 10. Enable podman socket
echo "Step 10: Enabling podman.socket..."
systemctl --user enable --now podman.socket

# 11. Setup dipen wrapper function
echo "Step 11: Setting up dipen wrapper function..."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIPEN_PATH="${SCRIPT_DIR}/dipen.sh"

MARKER_BEGIN="# >>> dipen wrapper >>>"
MARKER_END="# <<< dipen wrapper <<<"

write_dipen_block() {
    cat << EOF
${MARKER_BEGIN}
# Auto-generated by install-podman-on-debian.sh
# dipen wrapper: auto-cd untuk 'cd <service>' dan 'cd volume'
dipen() {
    local script="${DIPEN_PATH}"
    case "\$1" in
        cd)
            shift
            if [[ "\$1" == "volume" ]]; then
                shift
                local vol_dir="\$HOME/.local/share/containers/storage/volumes"
                if [[ -d "\$vol_dir" ]]; then
                    builtin cd "\$vol_dir"
                    echo "📁 \$vol_dir"
                    echo
                    if [[ -n "\$1" ]]; then
                        ls -lh | grep -i "\$1"
                    else
                        ls -lh
                    fi
                else
                    echo "Error: Volume directory not found: \$vol_dir"
                    return 1
                fi
            else
                local target
                target=\$("\$script" cd "\$@" 2>/dev/null | grep -oP '(?<=^\\s{2}cd ).*' | head -1)
                if [[ -n "\$target" && -d "\$target" ]]; then
                    builtin cd "\$target"
                else
                    "\$script" cd "\$@"
                fi
            fi
            ;;
        *)
            "\$script" "\$@"
            ;;
    esac
}
${MARKER_END}
EOF
}

update_shell_rc() {
    local shell_rc="$1"
    local shell_name="$2"
    
    if [ ! -f "$shell_rc" ]; then
        echo "ℹ️  $shell_rc not found, skipping $shell_name"
        return 0
    fi
    
    cp "$shell_rc" "${shell_rc}.bak.$(date +%Y%m%d_%H%M%S)"
    echo "📦 Backed up $shell_rc"
    
    if grep -qE "^\s*alias\s+dipen=" "$shell_rc" 2>/dev/null; then
        sed -i.bak -E "/^\s*alias\s+dipen=/d" "$shell_rc"
        echo "🗑️  Removed old 'alias dipen=' from $shell_rc"
    fi
    
    if grep -qE "^# Digital Independence - dipen$" "$shell_rc" 2>/dev/null; then
        sed -i.bak -E "/^# Digital Independence - dipen$/d" "$shell_rc"
        echo "🗑️  Removed old comment from $shell_rc"
    fi
    
    if grep -qF "$MARKER_BEGIN" "$shell_rc" 2>/dev/null; then
        sed -i.bak "/^${MARKER_BEGIN}$/,/^${MARKER_END}$/d" "$shell_rc"
        echo "🗑️  Removed old dipen wrapper block from $shell_rc"
    fi
    
    rm -f "${shell_rc}.bak" 2>/dev/null
    
    echo "" >> "$shell_rc"
    write_dipen_block >> "$shell_rc"
    echo "✅ Added dipen wrapper to $shell_rc"
}

# Bash setup
if [ -f "$DIPEN_PATH" ]; then
    chmod +x "$DIPEN_PATH" 2>/dev/null || true
    
    # Bash
    if [ -f ~/.bashrc ]; then
        update_shell_rc ~/.bashrc "bash"
    fi
    
    # Zsh
    if [ -f ~/.zshrc ]; then
        update_shell_rc ~/.zshrc "zsh"
    fi
else
    echo "⚠️  dipen.sh not found at: $DIPEN_PATH"
    echo "   Skipping dipen wrapper setup"
fi

echo ""
echo "💡 To use the dipen wrapper, either:"
echo "   - Restart your terminal, or"
echo "   - Run: source ~/.bashrc (or source ~/.zshrc)"
echo ""
echo "📝 Examples after setup:"
echo "   dipen list"
echo "   dipen up portainer"
echo "   dipen env nextcloud"
echo "   dipen cd nextcloud
echo "   dipen cd volume
echo "   dipen cd volume nextcloud
echo ""

echo "=========================================="
echo "Podman installation completed successfully!"
echo "=========================================="