services:
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DNSCRYPT_UPSTREAM_SERVERS=${DNSCRYPT_UPSTREAM_SERVERS}
      - DNSCRYPT_FALLBACK_RESOLVER=${DNSCRYPT_FALLBACK_RESOLVER}
      - DNSCRYPT_IGNORE_SYSTEM_DNS=${DNSCRYPT_IGNORE_SYSTEM_DNS}
      - DNSCRYPT_NETLOG_FILE=${DNSCRYPT_NETLOG_FILE}
      - DNSCRYPT_LOG_LEVEL=${DNSCRYPT_LOG_LEVEL}
      - DNSCRYPT_USE_SYSLOG=${DNSCRYPT_USE_SYSLOG}
      - DNSCRYPT_CACHE_SIZE=${DNSCRYPT_CACHE_SIZE}
      - DNSCRYPT_CACHE_MIN_TTL=${DNSCRYPT_CACHE_MIN_TTL}
      - DNSCRYPT_CACHE_MAX_TTL=${DNSCRYPT_CACHE_MAX_TTL}
      - DNSCRYPT_CACHE_NEGATIVE_MIN_TTL=${DNSCRYPT_CACHE_NEGATIVE_MIN_TTL}
      - DNSCRYPT_CACHE_NEGATIVE_MAX_TTL=${DNSCRYPT_CACHE_NEGATIVE_MAX_TTL}
      - DNSCRYPT_PREFER_IPV6=${DNSCRYPT_PREFER_IPV6}
      - DNSCRYPT_EDNS_PAYLOAD_SIZE=${DNSCRYPT_EDNS_PAYLOAD_SIZE}
      - DNSCRYPT_TIMEOUT=${DNSCRYPT_TIMEOUT}
      - DNSCRYPT_KEEPALIVE=${DNSCRYPT_KEEPALIVE}
      - DNSCRYPT_QUERY_LOG_FILE=${DNSCRYPT_QUERY_LOG_FILE}
      - DNSCRYPT_QUERY_LOG_FORMAT=${DNSCRYPT_QUERY_LOG_FORMAT}
      - DNSCRYPT_FORCE_TCP=${DNSCRYPT_FORCE_TCP}
      - DNSCRYPT_BLOCK_IPV6=${DNSCRYPT_BLOCK_IPV6}
    ports:
      - "5053:5053/udp"
      - "5053:5053/tcp"
    volumes:
      - './dnscrypt-proxy:/etc/dnscrypt-proxy'
    networks:
      - pihole_network
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # healthcheck:
    #  test: ["CMD", "nslookup", "google.com", "127.0.0.1"]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 3

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    depends_on:
      - dnscrypt-proxy
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
      WEBPASSWORD: ${WEBPASSWORD}
      
      # DNS Configuration
      FTLCONF_dns_upstreams: ${FTLCONF_dns_upstreams}
      FTLCONF_dns_blockESNI: ${FTLCONF_dns_blockESNI}
      FTLCONF_dns_EDNS0ECS: ${FTLCONF_dns_EDNS0ECS}
      FTLCONF_dns_ignoreLocalhost: ${FTLCONF_dns_ignoreLocalhost}
      FTLCONF_dns_showDNSSEC: ${FTLCONF_dns_showDNSSEC}
      FTLCONF_dns_analyzeOnlyAandAAAA: ${FTLCONF_dns_analyzeOnlyAandAAAA}
      FTLCONF_dns_piholePTR: ${FTLCONF_dns_piholePTR}
      FTLCONF_dns_replyWhenBusy: ${FTLCONF_dns_replyWhenBusy}
      FTLCONF_dns_blockTTL: ${FTLCONF_dns_blockTTL}
      FTLCONF_dns_domainNeeded: ${FTLCONF_dns_domainNeeded}
      FTLCONF_dns_expandHosts: ${FTLCONF_dns_expandHosts}
      FTLCONF_dns_bogusPriv: ${FTLCONF_dns_bogusPriv}
      FTLCONF_dns_dnssec: ${FTLCONF_dns_dnssec}
      FTLCONF_dns_interface: ${FTLCONF_dns_interface}
      FTLCONF_dns_listeningMode: ${FTLCONF_dns_listeningMode}
      FTLCONF_dns_queryLogging: ${FTLCONF_dns_queryLogging}
      FTLCONF_dns_port: ${FTLCONF_dns_port}
      FTLCONF_dns_localise: ${FTLCONF_dns_localise}
      
      # Cache
      FTLCONF_dns_cache_size: ${FTLCONF_dns_cache_size}
      FTLCONF_dns_cache_optimizer: ${FTLCONF_dns_cache_optimizer}
      FTLCONF_dns_cache_upstreamBlockedTTL: ${FTLCONF_dns_cache_upstreamBlockedTTL}

      # Blocking
      FTLCONF_dns_blocking_active: ${FTLCONF_dns_blocking_active}

      # Rate Limit
      FTLCONF_dns_rateLimit_count: ${FTLCONF_dns_rateLimit_count}
      FTLCONF_dns_rateLimit_interval: ${FTLCONF_dns_rateLimit_interval}

      # Database
      FTLCONF_database_maxDBdays: ${FTLCONF_database_maxDBdays}
      FTLCONF_database_network_expire: ${FTLCONF_database_network_expire}

      # Privacy
      FTLCONF_misc_privacylevel: ${FTLCONF_misc_privacylevel}

    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped
    networks:
      - pihole_network

networks:
  pihole_network:
    driver: bridge